### ISSUE TITLE
This package is not published in the NPM registry 

### ISSUE THREAD

**Issue by rrigoni** [streamr-dev/quick-dijkstra#2]
hey, 
This library is not published in the NPM library repository. Only the web assembly version is. 
I'm looking forward to use this in a backend node project. 

If possible to publish it I'd appreciate it. 

Thanks for this great and fast library.

**Comment by ptesavol** [comment]
Hi,
Thanks for noticing this, we'll try to find the time for publishing the native version on npm as well!

I think we had forgotten about the native version because we found out that for some reason, the webassembly version is faster even on nodejs, and had thus we have stopped using the native version internally.

If you want to use the webassembly version in nodejs while waiting for the native version to appear on npm, there is the example of doing just that at https://github.com/streamr-dev/quick-dijkstra/blob/master/examples/wasm/typescript-node/src/example.ts

**Comment by ptesavol** [comment]
Hi @rrigoni 

We have now published the native package at
https://www.npmjs.com/package/@streamr/quick-dijkstra

Let me know how it works!

**Comment by rrigoni** [comment]
Thanks a lot. I saw in the demo that you find the shortest path in between point 1 and 2. The current library published only has a method to find all the paths from a node. Do you have plans on adding a function to find all the paths from point a to b?

**Comment by ptesavol** [comment]
Sorry, but we don't currently have plans for adding a function to find all paths from point A to point B. Doing this would require a completely different algorithm, and the problem is not an easy one to solve either: https://stackoverflow.com/questions/9535819/find-all-paths-between-two-graph-nodes

Our current library has functions for finding all the shortest paths in a network, and for finding the shortest paths to all other nodes from node A. Our internal use case for the library is evaluating the quality of network topologies: the number of hops on the longest of the shortest paths lets us know the network diameter, and the cumulative delay on the same path gives us a good estimate of the propagation delay when doing broadcasting.
